/**
 * 
 */
package com.smansoft.sl.exceptions;

/**
 * 
 * @author SMan
 * 
 *         Exception, that is generated by Controllers
 *
 */
public class DaoException extends Exception {
	/**
     * 
     */
	private static final long serialVersionUID = -638034941631141563L;

	/**
     * 
     */
	public DaoException() {
	}

	/**
	 * 
	 * @param message
	 */
	public DaoException(String message) {
		super(message);
	}

	/**
	 * 
	 * @param message
	 * @param cause
	 */
	public DaoException(String message, Throwable cause) {
		super(message, cause);
	}
}
