CREATE TABLE users (id BIGINT AUTO_INCREMENT NOT NULL, email VARCHAR(255) NOT NULL UNIQUE, enabled TINYINT(1) default 0 NOT NULL, password VARCHAR(255) NOT NULL, sex INTEGER NOT NULL, user_address VARCHAR(255) NOT NULL, user_login VARCHAR(255) NOT NULL UNIQUE, user_name VARCHAR(255) NOT NULL, PRIMARY KEY (id))
CREATE INDEX users_id ON users (id)
CREATE INDEX users_user_login ON users (user_login)
CREATE INDEX users_email ON users (email)
CREATE TABLE user_roles (id BIGINT AUTO_INCREMENT NOT NULL, user_role_type INTEGER NOT NULL, user_id BIGINT, PRIMARY KEY (id))
CREATE INDEX user_roles_id ON user_roles (id)
CREATE INDEX user_roles_user_id ON user_roles (user_id)
ALTER TABLE users ADD CONSTRAINT UNQ_users_0 UNIQUE (id, user_login, email)
ALTER TABLE user_roles ADD CONSTRAINT UNQ_user_roles_0 UNIQUE (id)
ALTER TABLE user_roles ADD CONSTRAINT FK_user_roles_user_id FOREIGN KEY (user_id) REFERENCES users (id)
