/**
 * 
 */
package com.smansoft.sl.exceptions;

/**
 * @author SMan
 *
 *	Exception, that is generated by Checkers
 *
 */
public class CheckersException extends Exception {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3228189739206883683L;

	/**
	 * 
	 */
	public CheckersException() {
	}

	/**
	 * 
	 * @param message
	 */
	public CheckersException(String message) {
		super(message);
	}

	/**
	 * 
	 * @param message
	 * @param cause
	 */
	public CheckersException(String message, Throwable cause) {
		super(message, cause);
	}

}
