/**
 * 
 */
package com.smansoft.sl.exceptions;

/**
 * 
 * @author SMan
 * 
 *         Exception, that is generated by Controllers
 *
 */
public class ControllersException extends Exception {
	/**
     * 
     */
	private static final long serialVersionUID = -638034941631141563L;

	/**
     * 
     */
	public ControllersException() {
	}

	/**
	 * 
	 * @param message
	 */
	public ControllersException(String message) {
		super(message);
	}

	/**
	 * 
	 * @param message
	 * @param cause
	 */
	public ControllersException(String message, Throwable cause) {
		super(message, cause);
	}
}
