/**
 * 
 */
package com.smansoft.sl.exceptions;

/**
 * 
 * @author SMan
 *
 *         Exception, that is generated by Services
 *
 */
public class ServicesException extends Exception {
	
	/**
     * 
     */
	private static final long serialVersionUID = 2187407306943069327L;

	/**
     * 
     */
	public ServicesException() {
	}

	/**
	 * 
	 * @param message
	 */
	public ServicesException(String message) {
		super(message);
	}

	/**
	 * 
	 * @param message
	 * @param cause
	 */
	public ServicesException(String message, Throwable cause) {
		super(message, cause);
	}
}
